name: Pull-Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Run gradle build
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: tests
          path: /Users/runner/work/DireKt/DireKt/build/reports/tests/*
          if-no-files-found: warn
